import { useEffect, useMemo, useState } from 'react';
import { getAllBookProgress } from '../lib/db.js';
import { CHALLENGE_DAYS } from '../lib/pagination.js';
import { ArrowLeftIcon, TrophyIcon, CalendarIcon, ClockIcon } from './Icons.jsx';
import BookCover from './BookCover.jsx';

const LEVEL_ORDER = ['Beginner', 'Intermediate', 'Advanced'];
const LEVEL_CLASS = {
  Beginner: 'beginner',
  Intermediate: 'intermediate',
  Advanced: 'advanced',
};
// A friendly Korean label + difficulty dots (out of 3) so beginners can
// gauge a book at a glance without knowing the English level names.
const LEVEL_INFO = {
  Beginner: { label: '쉬워요', dots: 1 },
  Intermediate: { label: '보통', dots: 2 },
  Advanced: { label: '도전', dots: 3 },
};

const BEGINNER_WPM = 130; // conservative reading pace for the daily-time estimate

/** Rough minutes/day to finish a book within one CHALLENGE_DAYS cycle. */
function dailyMinutes(wordCount) {
  return Math.max(5, Math.round(wordCount / CHALLENGE_DAYS / BEGINNER_WPM));
}

/**
 * Library home: a colorful bookshelf of the built-in public-domain books
 * (bundled JSON, generated by scripts/build-books.mjs), grouped into
 * color-coded level sections. Each book shows its own cover art, a friendly
 * difficulty label, and an approachable "~N min/day" pace for the CHALLENGE_DAYS-day
 * challenge. Books matching the learner's level-test result are flagged
 * "Recommended for you", and the first Beginner book is suggested for
 * absolute newcomers.
 */
export default function BookLibraryScreen({ readingLevel, onOpenBook, onBack }) {
  const [books, setBooks] = useState(null); // null = loading
  const [progressByBook, setProgressByBook] = useState({});
  const [error, setError] = useState('');

  useEffect(() => {
    let alive = true;
    Promise.all([
      fetch(`${import.meta.env.BASE_URL}books/index.json`).then((r) => {
        if (!r.ok) throw new Error('index fetch failed');
        return r.json();
      }),
      getAllBookProgress(),
    ])
      .then(([index, progress]) => {
        if (!alive) return;
        setBooks(index);
        const map = {};
        progress.forEach((p) => {
          map[p.bookId] = p;
        });
        setProgressByBook(map);
      })
      .catch(() => {
        if (alive) setError('Could not load the Library. Please try again.');
      });
    return () => {
      alive = false;
    };
  }, []);

  const groupedByLevel = useMemo(() => {
    if (!books) return [];
    return LEVEL_ORDER.map((level) => ({
      level,
      books: books.filter((b) => b.level === level),
    })).filter((g) => g.books.length > 0);
  }, [books]);

  const anyStarted = books
    ? books.some((b) => (progressByBook[b.id]?.completedChapterIndices?.length || 0) > 0 || progressByBook[b.id]?.flatIndex)
    : false;
  const firstBeginner = books?.find((b) => b.level === 'Beginner');

  return (
    <section>
      <button className="back-link" onClick={onBack}>
        <ArrowLeftIcon size={16} /> Back home
      </button>

      <div className="screen-heading">
        <h2>Library</h2>
        <span className="count">무료 · 바로 읽기</span>
      </div>

      {/* Friendly starter nudge for absolute beginners. */}
      {!anyStarted && firstBeginner && (
        <button
          className="starter-banner"
          onClick={() => onOpenBook(firstBeginner.id)}
        >
          <BookCover bookId={firstBeginner.id} size="sm" />
          <span className="starter-banner-body">
            <span className="starter-banner-label">처음이신가요?</span>
            <strong>{firstBeginner.title}</strong>
            <span className="muted small">
              가장 쉬운 책부터 가볍게 시작해보세요 · 하루 약 {dailyMinutes(firstBeginner.wordCount)}분
            </span>
          </span>
        </button>
      )}

      {error && <div className="error-box">{error}</div>}

      {books === null && !error && (
        <div className="card">
          <div className="skeleton skeleton-title" />
          <div className="skeleton skeleton-line" />
          <div className="skeleton skeleton-line w-80" />
        </div>
      )}

      {groupedByLevel.map((group) => (
        <div className={`level-section level-section-${LEVEL_CLASS[group.level]}`} key={group.level}>
          <div className="level-section-header">
            <span className="level-dot" />
            {group.level}
            <span className="level-section-hint">{LEVEL_INFO[group.level].label}</span>
          </div>

          {group.books.map((book) => {
            const progress = progressByBook[book.id];
            const chaptersDone = progress?.completedChapterIndices?.length || 0;
            const started = chaptersDone > 0 || !!progress?.flatIndex;
            const pct = book.chapterCount
              ? Math.min(100, Math.round((chaptersDone / book.chapterCount) * 100))
              : 0;
            const levelClass = LEVEL_CLASS[book.level] || 'beginner';
            const info = LEVEL_INFO[book.level] || LEVEL_INFO.Beginner;

            return (
              <button
                key={book.id}
                className={`book-card book-card-${levelClass}`}
                onClick={() => onOpenBook(book.id)}
              >
                <BookCover bookId={book.id} />
                <div className="book-card-body">
                  <div className="book-card-head">
                    <h3>{book.title}</h3>
                    <span className={`pill pill-level-${levelClass}`}>{book.level}</span>
                  </div>
                  <p className="muted small book-card-author">
                    {book.author} · {book.year}
                  </p>

                  <div className="book-card-meta">
                    <span className="meta-chip">
                      <ClockIcon size={12} /> 하루 ~{dailyMinutes(book.wordCount)}분
                    </span>
                    <span className="meta-chip">
                      <CalendarIcon size={12} /> {CHALLENGE_DAYS}일 완독
                    </span>
                    <span className="difficulty-meter" title={info.label} aria-label={`난이도 ${info.label}`}>
                      {[0, 1, 2].map((i) => (
                        <span key={i} className={`diff-dot ${i < info.dots ? 'on' : ''}`} />
                      ))}
                    </span>
                  </div>

                  {readingLevel === book.level && (
                    <p className="recommended-tag">
                      <TrophyIcon size={12} /> Recommended for you
                    </p>
                  )}

                  <p className="small book-card-desc">{book.description}</p>

                  {started ? (
                    <>
                      <div className="progress-track" style={{ marginBottom: 4 }}>
                        <div className="progress-fill" style={{ width: `${pct}%` }} />
                      </div>
                      <p className="muted small continue-line" style={{ margin: 0 }}>
                        {progress.bookCompleted
                          ? '✓ 완독! 언제든 다시 읽기'
                          : `이어 읽기 · ${pct}% 진행`}
                      </p>
                    </>
                  ) : (
                    <p className="muted small" style={{ margin: 0 }}>
                      {book.chapterCount}개 챕터 · {book.wordCount.toLocaleString()} 단어
                    </p>
                  )}
                </div>
              </button>
            );
          })}
        </div>
      ))}
    </section>
  );
}
