import { useEffect, useState } from 'react';
import { getAllBookProgress } from '../lib/db.js';
import { LibraryIcon, ArrowLeftIcon, TrophyIcon } from './Icons.jsx';

/**
 * Library home: lists the built-in public-domain books (bundled JSON,
 * generated by scripts/build-books.mjs) with reading-progress bars for
 * books the learner has already started. If a level-test result is on
 * file, books matching that level are flagged "Recommended for you".
 */
export default function BookLibraryScreen({ readingLevel, onOpenBook, onBack }) {
  const [books, setBooks] = useState(null); // null = loading
  const [progressByBook, setProgressByBook] = useState({});
  const [error, setError] = useState('');

  useEffect(() => {
    let alive = true;
    Promise.all([
      fetch(`${import.meta.env.BASE_URL}books/index.json`).then((r) => {
        if (!r.ok) throw new Error('index fetch failed');
        return r.json();
      }),
      getAllBookProgress(),
    ])
      .then(([index, progress]) => {
        if (!alive) return;
        setBooks(index);
        const map = {};
        progress.forEach((p) => {
          map[p.bookId] = p;
        });
        setProgressByBook(map);
      })
      .catch(() => {
        if (alive) setError('Could not load the Library. Please try again.');
      });
    return () => {
      alive = false;
    };
  }, []);

  return (
    <section>
      <button className="back-link" onClick={onBack}>
        <ArrowLeftIcon size={16} /> Back home
      </button>

      <div className="screen-heading">
        <h2>Library</h2>
        <span className="count">Public domain · read free</span>
      </div>

      {error && <div className="error-box">{error}</div>}

      {books === null && !error && (
        <div className="card">
          <div className="skeleton skeleton-title" />
          <div className="skeleton skeleton-line" />
          <div className="skeleton skeleton-line w-80" />
        </div>
      )}

      {books?.map((book) => {
        const progress = progressByBook[book.id];
        const chaptersDone = progress?.completedChapterIndices?.length || 0;
        const pct = book.chapterCount
          ? Math.min(100, Math.round((chaptersDone / book.chapterCount) * 100))
          : 0;
        return (
          <button
            key={book.id}
            className="book-card"
            onClick={() => onOpenBook(book.id)}
          >
            <div className="book-card-icon">
              <LibraryIcon size={22} />
            </div>
            <div className="book-card-body">
              <div className="book-card-head">
                <h3>{book.title}</h3>
                <span className="pill pill-register-neutral">{book.level}</span>
              </div>
              <p className="muted small book-card-author">
                {book.author} · {book.year}
              </p>
              {readingLevel === book.level && (
                <p className="recommended-tag">
                  <TrophyIcon size={12} /> Recommended for you
                </p>
              )}
              <p className="small book-card-desc">{book.description}</p>
              {chaptersDone > 0 ? (
                <>
                  <div className="progress-track" style={{ marginBottom: 4 }}>
                    <div className="progress-fill" style={{ width: `${pct}%` }} />
                  </div>
                  <p className="muted small" style={{ margin: 0 }}>
                    {progress.bookCompleted
                      ? 'Finished — read again anytime'
                      : `Chapter ${Math.min((progress.chapterIndex ?? 0) + 1, book.chapterCount)} of ${book.chapterCount} · Continue reading`}
                  </p>
                </>
              ) : (
                <p className="muted small" style={{ margin: 0 }}>
                  {book.chapterCount} chapters · {book.wordCount.toLocaleString()} words
                </p>
              )}
            </div>
          </button>
        );
      })}
    </section>
  );
}
